### ISSUE TITLE
how can i create a reference to other document?

### ISSUE THREAD

**Issue by Giuan0** [rumkin/mongoose-map#1]
I wanna make a MongooseMap with a reference id tho other document as key, and two more variables as values... like:
var variable = {
    value1: String,
    value2:Number
}
var map = new Map();
map.set(_someId, variable);

_someId is a Schema.Types.ObjectId
how can a make a schema of this?

**Comment by rumkin** [comment]
Currently it's not possible to define schemas for maps.
